### ISSUE TITLE
[fds-data-table]: sortable columns

### ISSUE THREAD

**Issue by pnina** [Finastra/finastra-design-system#1043]
Enable table columns sort, it will be very useful
https://finastra.github.io/finastra-design-system/?path=/docs/data-display-data-table--data-table-default

**Comment by Ping-YUAN** [comment]
hello 
We have this feature. 
If you check the column definition [here](https://github.com/Finastra/finastra-design-system/tree/master/libs/web-components/data-table#style-for-columns), you can find the sortable parameter. Then you can set which column can be sortable

**Comment by pnina** [comment]
Hello,
Thanks, Yes I see this feature. 
The documentation is not clear...

**Comment by Ping-YUAN** [comment]
the storybook is mainly focus on demo. For more detail documentation. You can go to readme of data-table.
