### ISSUE TITLE
[WC:data-table]:get slected index

### ISSUE THREAD

**Issue by pnina** [Finastra/finastra-design-system#1058]
**Describe the bug**
`onFdsDataTableRowSelected` , we get the selected data from `event.detail` , needed to get also selected index in order to edit the selected data in dataSource.
https://github.com/Finastra/finastra-design-system/blob/master/libs/web-components/data-table/README.md

**Expected behavior**
get the selected index from `event.index`

**Additional context**
If there is another way to edit the selectedData in dataSource, please provide example or documentation

**Comment by Ping-YUAN** [comment]
You can set your own primary id for your datasource. so that you can handle by yourself.
