### ISSUE TITLE
[wc:chip] icon shouldn't be set through both property and slot

### ISSUE THREAD

**Issue by bcldvd** [Finastra/finastra-design-system#849]
**Describe the bug**
Currently, both icon and trailing icons can be set through properties **and** slots, which can be misleading for the developers using it.

**Expected behavior**
Should be set through either property or slot, not both

**Comment by code2nguyen** [comment]
trailing icon slot will override trailing icon property, so it is normal. I dont think we should change this behavior. 

There are many components expose both properties and slot for some reason. (example, with slot users are free to add content, htm, css with property, it is limited only for JS object).
