### ISSUE TITLE
Walk through / Popover component

### ISSUE THREAD

**Issue by bcldvd** [Finastra/finastra-design-system#859]
> [Open in MURAL](https://app.mural.co/t/finastrauxd7350/m/finastrauxd7350/1634918733969?wid=33-1656697453159) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> Sprint Planning(s) - Finastra
  

Design specifications: https://www.figma.com/file/E1Mb1556RT3HbAUVu2Q0LV/Finastra-design-system?node-id=107385%3A34387

Original guided tour component: https://github.com/Finastra/finastra-design-system/tree/feature/guided-tour-wc/libs/web-components/guided-tour

**Comment by code2nguyen** [comment]
Libraries help to build walk through/user guild: https://userguiding.com/blog/introjs-alternatives/

**Comment by code2nguyen** [comment]
PR WIP : https://github.com/Finastra/finastra-design-system/pull/862
