### ISSUE TITLE
[wizard]: stepper disappearing after refresh page

### ISSUE THREAD

**Issue by tehilamearchavi** [Finastra/finastra-design-system#865]
**Describe the bug**
[wizard]: stepper disappearing after refresh page 

**Screenshots**
![image](https://user-images.githubusercontent.com/41566558/191224921-04cfc1aa-7f06-4230-8869-f72608eba239.png)

**Comment by dorsaffrigui** [comment]
Hello @tehilamearchavi ,

Thanks for reporting this bug to us.I'am looking into it.
