### ISSUE TITLE
[web-component] - wizard can't requires the user to complete step previous

### ISSUE THREAD

**Issue by tehilamearchavi** [Finastra/finastra-design-system#881]
**Describe the bug**
wizard can't requires the user to complete previous steps before proceeding to following steps.

**Screenshots**
![image](https://user-images.githubusercontent.com/41566558/192757279-db83977c-ff17-4189-848d-6a908ba73d4a.png)

**Comment by Pi5rr5** [comment]
Expected behavior to be like material angular stepper -> [linear stepper](https://material.angular.io/components/stepper/overview#linear-stepper)

**Comment by Pi5rr5** [comment]
Fixed by #885
