### ISSUE TITLE
tree component

### ISSUE THREAD

**Issue by chenshuichao** [Finastra/finastra-design-system#892]
Is there any plan about tree component？

**Comment by Pi5rr5** [comment]
Hello @chenshuichao are you referring to a tree like this one [filter-tree](https://finastra.github.io/finastra-design-system/?path=/story/data-display-filter-tree--default) ?
If not can you share more details about your use case ?
Regards.

**Comment by chenshuichao** [comment]
https://www.syncfusion.com/javascript-ui-controls/js-treeview
@Pi5rr5

**Comment by Pi5rr5** [comment]
Thanks for the reply, as of today we don't have it planned but we will add it to our backlog. And we are always open for contribution ! 😉
