### ISSUE TITLE
[uxg-filter-tags] support data with label and value

### ISSUE THREAD

**Issue by pnina** [Finastra/finastra-design-system#923]
**Describe the solution you'd like**
I need to display different label then data, sample: label: ALL, value:OTHER

**Additional context**
As I see, there is no web-component for now.

**Comment by pnina** [comment]
for <uxg-filter-tags [data]
need add to Tag interface property of value:
export interface Tag {
    label: string;
    **value: string;**
    isSelected?: boolean;
    category?: string;
}

something like exists today on <uxg-filter-toggle
export interface ToggleBtn {
    label: string;
    value: string;
    matIcon?: string;
    isSelected?: boolean;
}

Note:
there is no alternative WC yet for <uxg-filter-tags

**Comment by pnina** [comment]
Hello,
the attribue is still missing after `npm unistall` and `npm install @finastra/angular-components`
![image](https://user-images.githubusercontent.com/825225/202896059-2c7b41b8-e1f2-4b08-beb2-3ebeb2087a6c.png)

besides, had to use flag --legacy-peer-deps, because latest @finastra/angular-components requires angular 14.
Is there a fixed version using angular 13?

**Comment by bcldvd** [comment]
Angular component have not been released yet since the merge of the PR. Will make a release today.

However, we won't make a fix in angular 13
