### ISSUE TITLE
[wc:fds-breadcrumb] Support navigation

### ISSUE THREAD

**Issue by pnina** [Finastra/finastra-design-system#943]
**Describe the bug**
The example of breadcrumbs supports only design without any url

**Code sample**
https://finastra.github.io/finastra-design-system/?path=/docs/navigation-breadcrumb--default

**Expected behavior**
```html
<fds-breadcrumb items="items"></fds-breadcrumb>
```

```ts
items = [
    {
     label:"Home",
    url:"home"
    },
   {
     label:"Packages",
     url:"packages"
    },
]
```

**Additional context**
https://dev.to/zhiyueyi/create-a-simple-breadcrumb-in-angular-ag5
https://marco.dev/angular-breadcrumb

**Comment by blminami** [comment]
Additional feedback on breadcrumb wc:

- expose css variables to style the items (font, color, etc.)
- hover effect for links that are active 
- remove pointer for inactive links and current link

some use-cases:

![image](https://user-images.githubusercontent.com/20680686/201069513-aef35cdd-a6cb-419f-9b68-cffdf831e96c.png)

![image](https://user-images.githubusercontent.com/20680686/201069581-c00d7bb3-f63e-4d9c-bf11-f5e3bdab31e9.png)

![image](https://user-images.githubusercontent.com/20680686/201069474-c0c0c268-1245-4e2f-aeab-aa9e332ffd05.png)

**Comment by bcldvd** [comment]
Pattern to have breadcrumb in app bar is deprecated.
Hence the Product Name remains in app bar while the (rest of) breadcrumb can be placed wherever in the app.

(more to come ... we're still discussing it 😄 ... but hopefully we'll tackle it within the next two weeks ;) )
