### ISSUE TITLE
Palette file contains a typo

### ISSUE THREAD

**Issue by alicelebidev** [Finastra/finastra-design-system#991]
**Describe the bug**
_palette.scss file contains a typo where reference to a variable is not correct set.

**To Reproduce**

1. Go to file _palette.scss
2. Search for this line `75: rgba(var(--color-error-ligther), 1),`
3. Variable name should be `--color-error-lighter`

**Code sample**
Code snippet or link to a live editor (StackBlitz / CodePen) reproducing the bug.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13241089/205677629-5f249e03-7bf3-4574-9ba5-0f8418c05039.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bcldvd** [comment]
Thank you for the keen eye @alicelebidev !!!

I made a fix, will be released next week probably (tell us if you'd need it sooner).

Next time, feel free to make a fork and submit us a Pull Request, we'd be very happy to review it and count you in our trusted contributors community!
